export default {
  Tickets: [
    {
      id: 1,
      requester_name: 'Jerry',
      title: 'routing error',
      feedback: 'cannot route to detail page.',
      assignee: 'Tommy',
      issued_type: 'bug',
      status: 'solved',
      request_date: 'Jun 3,  2022',
      solved_date: 'Jun 5,  2022',
    },
    {
      id: 2,
      requester_name: 'Kathy',
      title: 'add new form field',
      feedback:'please add a new field named assignee position in ticket request form',
      assignee: 'Amy',
      issued_type: 'task',
      status: 'open',
      request_date: 'Aug 15,  2022',
      solved_date: null,
    },
    {
      id: 3,
      requester_name: 'Paul',
      title: 'routing error',
      feedback: 'cannot route to detail page.',
      assignee: 'Tommy',
      issued_type: 'bug',
      status: 'solved',
      request_date: 'Jun 3,  2022',
      solved_date: 'Jun 5,  2022',
    },
    {
      id: 4,
      requester_name: 'John',
      title: 'lagging list',
      feedback: 'ticket list is lagging while scrolling the list',
      assignee: 'Wendy Vue',
      issued_type: 'bug',
      status: 'in-progress',
      request_date: 'Sep 13,  2022',
      solved_date: null,
    },
    {
      id: 5,
      requester_name: 'Catherine',
      title: 'lagging list',
      feedback: 'ticket list is lagging while scrolling the list',
      assignee: 'Wendy Vue',
      issued_type: 'bug',
      status: 'closed',
      request_date: 'Sep 13,  2022',
      solved_date: 'Sep 20,  2022',
    },
    {
      id: 6,
      requester_name: 'Jerry',
      title: 'routing error',
      feedback: 'cannot route to detail page.',
      assignee: 'Tommy',
      issued_type: 'bug',
      status: 'solved',
      request_date: 'Jun 3,  2022',
      solved_date: 'Jun 5,  2022',
    },
    {
      id: 7,
      requester_name: 'Kathy',
      title: 'add new form field',
      feedback:'please add a new field named assignee position in ticket request form',
      assignee: 'Amy',
      issued_type: 'task',
      status: 'open',
      request_date: 'Aug 15,  2022',
      solved_date: null,
    },
    {
      id: 8,
      requester_name: 'Paul',
      title: 'routing error',
      feedback: 'cannot route to detail page.',
      assignee: 'Tommy',
      issued_type: 'bug',
      status: 'solved',
      request_date: 'Jun 3,  2022',
      solved_date: 'Jun 5,  2022',
    },
    {
      id: 9,
      requester_name: 'John',
      title: 'lagging list',
      feedback: 'ticket list is lagging while scrolling the list',
      assignee: 'Wendy Vue',
      issued_type: 'bug',
      status: 'in-progress',
      request_date: 'Sep 13,  2022',
      solved_date: null,
    },
    {
      id: 10,
      requester_name: 'Catherine',
      title: 'lagging list',
      feedback: 'ticket list is lagging while scrolling the list',
      assignee: 'Wendy Vue',
      issued_type: 'bug',
      status: 'closed',
      request_date: 'Sep 13,  2022',
      solved_date: 'Sep 20,  2022',
    },
  ],
  Developers: [
    {
      key: 'd_001',
      value: 'Amy',
      position: 'developer',
    },
    {
      key: 'd_002',
      value: 'John',
      position: 'team lead',
    },
    {
      key: 'd_003',
      value: 'Tommy',
      position: 'junior programmer',
    },
  ],
  IssueTypes: [
    {
      key: '0001',
      value: 'bug',
    },
    {
      key: '0002',
      value: 'task',
    },
  ],
  Status: [
    {
      key: 's_001',
      value: 'open',
    },
    {
      key: 's_002',
      value: 'closed',
    },
    {
      key: 's_003',
      value: 'in-progress',
    },
    {
      key: 's_004',
      value: 'solved',
    },
  ],
};
